version: '3'
services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  app:
    container_name: docker-node
    restart: always
    build: .
    ports:
      - '8080:8080'
    environment:
      REDIS_HOST: redis
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
